version: "3.1"
services:
  copsi:
    image: "collaborativedhs/copsi:3.0.1"
    container_name: copsi
    hostname: copsi
    restart: always
    ports:
      - "8090:80"
    networks:
      - copsi
    volumes:
      - /data/copsi/config:/usr/local/apache2/htdocs/assets/config
      # uncomment the following line in case you need to change the base href (default: copsi)
      #- /data/copsi/html/index.html:/usr/local/apache2/htdocs/index.html    

networks:
    copsi:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.16.0.0/16
